#!/bin/bash
# batch run

#sed 's/randomnumberseed 1/randomnumber $i/g' config-baseline.txt 

#./corvid config_A1
declare -a seeds
for ((n=1;n<=9; n++)) 
do 
  seeds+=($RANDOM)
done 

for s in ${seeds[@]}
do
   echo $s
done > seeds.txt 

seeds=(22624 14486 10520 32058 3227 15022 6091 17392 24335 32607 17392)
#seeds=(6091)

for seed in ${seeds[@]}
do
for d in 28
do
 for X in 10000  
 do  
  for i in 30 
   do 
    echo "${seed}"
     SF="C2-D${i}-S${seed}-X${X}-T${d}-summary.txt"
     LF="C2-D${i}-S${seed}-X${X}-T${d}-log.txt"
     TF="C2-D${i}-S${seed}-X${X}-T${d}-tracts.txt"
     IDF="C2-D${i}-S${seed}-X${X}-T${d}-individuals.txt"
    sed  "s/ssdd/${seed}/g;s/ssff/${SF}/g;s/llff/${LF}/g;s/ttff/${TF}/g;s/iiff/${IDF}/g;s/rrdd/${i}/g;s/sszz/${X}/g;s/ssaa/${d}/g;" config-C2 > "config_c2_${i}_${seed}_${X}_${d}"
    ./corvid "config_c2_${i}_${seed}_${X}_${d}"
    done
  done
done
done

